export const productList = [
  [
    {
      user_id: 100,
      company_name: "Microbrasserie A L'Abordage",
      user_type_id: 3,
    },
    {
      user_id: 101,
      company_name: "Microbrasserie Riverbend",
      user_type_id: 3,
    },
    {
      user_id: 102,
      company_name: "company1nov",
      user_type_id: 3,
    },
    {
      user_id: 103,
      company_name: "Lagerbräu",
      user_type_id: 3,
    },
    {
      user_id: 104,
      company_name: "Microbrasserie Emporium",
      user_type_id: 3,
    },
  ],
  [
    {
      user_id: 100,
      company_name: null,
      business_name: "La Station des Bieres et Fromagerie Ste-Julie",
      added_by: 4,
      user_type_id: 4,
      business_category_id: 1,
    },
    {
      user_id: 101,
      company_name: null,
      business_name: "Au Toit Rouge",
      added_by: 4,
      user_type_id: 4,
      business_category_id: 1,
    },
    {
      user_id: 102,
      company_name: null,
      business_name: "La Barik",
      added_by: 4,
      user_type_id: 4,
      business_category_id: 1,
    },
    {
      user_id: 103,
      company_name: null,
      business_name: "Le Biérologue",
      added_by: 4,
      user_type_id: 4,
      business_category_id: 1,
    },
    {
      user_id: 104,
      company_name: null,
      business_name: "Accommodation Gaz Store",
      added_by: 134,
      user_type_id: 4,
      business_category_id: null,
    },
  ],
  [
    {
      id: 1,
      name: "Convenience Store",
      user_id: 100,
    },
    {
      id: 2,
      user_id: 101,
      name: "Liquor Store",
    },
    {
      id: 3,
      user_id: 102,
      name: "Bar",
    },
    {
      id: 4,
      user_id: 103,
      name: "Cafe",
    },
    {
      id: 5,
      user_id: 104,
      name: "Restaurant",
    },
  ],
  [
    {
      id: 120,
      product_name: "Berliner Weisse",
      product_type: "Beer",
      product_style: 13,
      product_format: 53,
      user_id: 100,
    },
    {
      id: 121,
      product_name: "Berliner Framboise",
      product_type: "Beer",
      product_style: 14,
      product_format: 53,
      user_id: 101,
    },
    {
      id: 122,
      product_name: "Bitter Rousse",
      product_type: "Beer",
      product_style: 21,
      product_format: 53,
      user_id: 102,
    },
    {
      id: 123,
      product_name: "Blanche clémentine",
      product_type: "Beer",
      product_style: 22,
      product_format: 53,
      user_id: 103,
    },
    {
      id: 124,
      product_name: "Double IPA",
      product_type: "Beer",
      product_style: 32,
      product_format: 53,
      user_id: 104,
    },
  ],
  [
    {
      product_type: "Beer",
      user_id: 100,
    },
  ],
  [
    {
      id: 1,
      user_id: 100,
      name: "Ale Blonde",
    },
    {
      id: 2,
      user_id: 101,
      name: "Ale brune",
    },
    {
      id: 3,
      user_id: 102,
      name: "Ale de blé Allemande",
    },
    {
      id: 4,
      user_id: 103,
      name: "Ale rousse",
    },
    {
      id: 5,
      user_id: 104,
      name: "Ale Rousse Allemande",
    },
  ],
  [
    {
      id: 1,
      user_id: 100,
      name: "Bottle 250ml x 12",
    },
    {
      id: 2,
      user_id: 101,
      name: "Bottle 250ml x 15",
    },
    {
      id: 3,
      user_id: 102,
      name: "Bottle 250ml x 24",
    },
    {
      id: 4,
      user_id: 103,
      name: "Bottle 250ml 6x3 pack",
    },
    {
      id: 5,
      user_id: 100,
      name: "Bottle 250ml 6x4 pack",
    },
  ],
  [
    {
      supplier_id: 238,
      retailer_id: 239,
      product_name: "Monastic Harmony",
      product_style_id: 1,
      user_id: 100,
      product_format_id: 11,
    },
    {
      supplier_id: 238,
      retailer_id: 239,
      product_name: "Mexican Chocolate",
      product_style_id: 122,
      user_id: 102,
      product_format_id: 53,
    },
    {
      supplier_id: 238,
      retailer_id: 239,
      product_name: "Mexican Chocolate",
      product_style_id: 122,
      user_id: 103,
      product_format_id: 53,
    },
    {
      supplier_id: 101,
      retailer_id: 106,
      product_name: "Berliner Weisse",
      product_style_id: 13,
      user_id: 104,
      product_format_id: 53,
    },
    {
      supplier_id: 238,
      retailer_id: 239,
      user_id: 100,
      product_name: "Mexican Chocolate",
      product_style_id: 122,
      product_format_id: 53,
    },
  ],
];
